In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
url = "https://raw.githubusercontent.com/ahmedmoustafa/gene-expression-datasets/refs/heads/main/datasets/breast_cancer/breast_cancer.tsv"

In [3]:
import pandas as pd 

df = pd.read_csv(url, delimiter='\t')
df.head()

,ID_REF,Ctrl_1,Ctrl_2,Ctrl_3,Ctrl_4,Ctrl_5,Ctrl_6,Ctrl_7,Ctrl_8,Ctrl_9,...,BRCA1_8,BRCA1_9,BRCA2_1,BRCA2_2,BRCA2_3,BRCA2_4,BRCA2_5,BRCA2_6,BRCA2_7,BRCA2_8
0,1007_s_at,5.435103,5.008329,5.231527,5.031998,4.985290,6.142334,5.004434,5.411374,5.116332,...,5.054647,5.436515,5.344158,5.535932,5.540570,5.351259,5.646676,5.459020,5.289579,5.471318
1,1053_at,7.733028,7.777820,8.454897,8.019996,6.771159,6.955941,8.672567,5.346701,7.446739,...,7.167523,7.124138,6.593446,6.704074,7.557785,7.502817,7.518530,7.804092,7.434408,6.742815
2,117_at,4.145030,4.291544,4.379873,4.478607,4.529217,4.866893,4.274667,4.726105,4.533870,...,5.174017,5.487212,4.193879,4.597297,4.634234,4.518198,5.785436,4.183698,4.249086,4.489095
3,121_at,6.072102,6.128962,6.334051,5.892953,6.092043,6.625896,5.474148,6.113826,6.053390,...,6.312075,5.850466,6.021123,5.957165,6.439730,5.790195,6.411545,6.368793,6.064548,5.786747
4,1255_g_at,3.880355,3.741581,3.671371,3.721694,3.561725,3.811393,3.765680,3.621480,3.631466,...,3.873683,3.666752,3.682486,3.604368,3.706883,3.693750,3.822298,3.863786,3.619982,3.692030

In [4]:
print(df.shape)

(22277, 27)

In [5]:
# rows = patients
# columns = genes

df_ml = df.set_index("ID_REF").T

In [6]:
df_ml

ID_REF,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,1431_at,...,AFFX-r2-Ec-bioD-3_at,AFFX-r2-Ec-bioD-5_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at
Ctrl_1,5.435103,7.733028,4.145030,6.072102,3.880355,8.244002,3.995260,3.894231,10.119957,3.601694,...,12.235321,12.048695,13.735933,12.943992,3.882484,3.687871,3.691945,3.597827,4.021169,3.863777
Ctrl_2,5.008329,7.777820,4.291544,6.128962,3.741581,7.863173,3.934177,4.029559,11.296112,3.667243,...,12.064975,11.723586,13.578497,12.718998,4.068816,3.844632,3.960012,3.698280,3.904696,3.706466
Ctrl_3,5.231527,8.454897,4.379873,6.334051,3.671371,6.393570,4.026327,4.190585,8.828152,3.677338,...,11.551538,11.231814,13.551922,12.607748,3.931702,3.886046,3.731470,3.542740,3.960613,3.667430
Ctrl_4,5.031998,8.019996,4.478607,5.892953,3.721694,7.702444,4.159512,3.866083,11.196986,3.741057,...,11.960667,11.875629,13.650233,12.830786,4.012594,3.825091,3.820569,3.825216,3.916462,3.454849
Ctrl_5,4.985290,6.771159,4.529217,6.092043,3.561725,8.419192,4.085102,4.022460,12.239574,3.750783,...,12.304293,12.192493,13.804774,13.117024,3.971345,3.755792,3.759238,3.674284,3.758008,3.743802
Ctrl_6,6.142334,6.955941,4.866893,6.625896,3.811393,8.918576,4.120550,3.759336,11.413107,3.881524,...,11.109353,9.352556,12.653236,11.890298,4.083088,3.894394,3.830467,3.765297,3.859202,3.631228
Ctrl_7,5.004434,8.672567,4.274667,5.474148,3.765680,7.331135,3.961010,4.017860,9.783332,3.682349,...,11.913567,11.683333,13.574553,12.720251,4.043005,3.866237,3.755747,3.608352,3.813247,3.638798
Ctrl_8,5.411374,5.346701,4.726105,6.113826,3.621480,9.121967,4.079779,3.982694,10.602650,3.601726,...,12.222848,12.087999,13.610194,12.912414,4.042596,3.714798,3.675765,3.782761,3.887486,3.655408
Ctrl_9,5.116332,7.446739,4.533870,6.053390,3.631466,8.420907,3.949763,3.994140,10.701429,3.648642,...,12.040155,11.716284,13.528714,12.794530,3.944137,3.759497,3.803606,3.704745,3.869344,3.673831
BRCA1_1,5.284818,6.360131,10.066502,6.294137,3.681249,8.145534,4.228227,4.046465,11.819785,3.725276,...,12.296647,12.062512,13.832867,13.224076,3.868354,3.711933,3.667778,3.585338,3.806914,3.579744
BRCA1_2,5.182803,7.902398,4.474714,6.042888,3.685221,7.580642,3.993735,4.147528,11.884071,3.679578,...,11.101218,10.727166,12.965246,11.967667,4.007888,3.807003,3.942536,3.758908,3.727186,3.666670
BRCA1_3,5.456290,7.961362,4.330880,5.740115,3.596858,7.923142,3.977801,3.738986,11.806669,3.678737,...,12.024114,11.834278,13.773880,12.981848,3.923956,3.698615,3.683854,3.669560,3.920549,3.654250
BRCA1_4,5.048849,8.229409,4.344952,5.674960,3.625883,7.775083,3.889287,3.924827,9.783927,3.570605,...,12.016825,11.834547,13.512184,12.792800,3.734998,3.614176,3.724816,3.748796,3.970004,3.720680
BRCA1_5,5.087956,8.121414,4.355170,5.823128,3.564516,7.826739,4.154478,3.979360,8.688305,3.681539,...,12.245110,12.016573,13.725189,12.963478,4.066847,3.900176,3.887271,3.635982,3.698335,3.719636
BRCA1_6,4.848453,7.958433,4.535119,6.300954,3.585755,8.275643,4.054460,4.137502,9.797972,3.672554,...,11.968203,11.713628,13.610190,12.736113,4.041965,3.793307,3.824060,3.719136,3.734669,3.666160
BRCA1_7,5.340628,6.686733,11.946442,6.160760,3.676803,8.471139,3.948406,3.858988,11.154461,3.686303,...,12.162033,11.956013,13.649715,12.945990,3.823251,3.859160,3.718513,3.692245,3.959998,3.662488
BRCA1_8,5.054647,7.167523,5.174017,6.312075,3.873683,8.621004,4.138326,3.889807,9.228351,3.694851,...,12.235882,12.013282,13.609799,12.786031,4.056088,3.879627,3.805192,3.839517,3.843121,3.541297
BRCA1_9,5.436515,7.124138,5.487212,5.850466,3.666752,8.199452,3.975198,3.892871,11.128237,3.705859,...,12.165624,11.879274,13.638843,12.831620,3.846474,3.719482,3.582174,3.576707,3.795824,3.606803
BRCA2_1,5.344158,6.593446,4.193879,6.021123,3.682486,8.079504,3.911734,4.109134,11.706726,3.852377,...,11.791995,11.491159,13.474309,12.771478,3.815209,3.694363,3.575282,3.646838,3.579390,3.655582
BRCA2_2,5.535932,6.704074,4.597297,5.957165,3.604368,8.674645,4.084331,3.927564,11.781463,3.760567,...,12.006164,11.656128,13.637365,12.850998,3.901003,3.878833,3.718253,3.620707,3.728518,3.590841
BRCA2_3,5.540570,7.557785,4.634234,6.439730,3.706883,8.158692,4.178522,3.977503,9.537391,3.770318,...,11.692604,11.372583,13.395606,12.647765,3.846352,3.786138,3.722546,3.742525,3.906150,3.544716
BRCA2_4,5.351259,7.502817,4.518198,5.790195,3.693750,7.248585,3.944306,4.050683,10.537709,3.644094,...,11.896274,11.750792,13.640210,12.943757,4.151427,3.789401,3.823395,3.732035,3.801924,3.665411
BRCA2_5,5.646676,7.518530,5.785436,6.411545,3.822298,7.991346,4.175725,3.951112,9.951454,3.708952,...,11.993184,11.689889,13.666230,12.898545,3.766982,3.823888,3.806543,3.603609,3.810379,3.571417
BRCA2_6,5.459020,7.804092,4.183698,6.368793,3.863786,8.281895,3.848689,3.879350,11.249952,3.803046,...,11.706659,11.299600,13.363030,12.446828,3.936198,3.941091,3.804492,3.616117,3.771551,3.634231
BRCA2_7,5.289579,7.434408,4.249086,6.064548,3.619982,8.035926,4.005591,3.974861,11.442377,3.847964,...,11.843285,11.530820,13.712898,12.955113,4.080084,3.704182,3.821633,3.546395,3.665810,3.602096
BRCA2_8,5.471318,6.742815,4.489095,5.786747,3.692030,8.610116,4.191129,3.988412,11.768811,3.857082,...,11.976373,11.633021,13.586853,12.883775,3.830499,3.788163,3.675097,3.562896,3.751692,3.570864

In [7]:
df_ml['1053_at'].shape

(26,)

In [8]:
for col in df_ml.index:
    print(col)

Ctrl_1
Ctrl_2
Ctrl_3
Ctrl_4
Ctrl_5
Ctrl_6
Ctrl_7
Ctrl_8
Ctrl_9
BRCA1_1
BRCA1_2
BRCA1_3
BRCA1_4
BRCA1_5
BRCA1_6
BRCA1_7
BRCA1_8
BRCA1_9
BRCA2_1
BRCA2_2
BRCA2_3
BRCA2_4
BRCA2_5
BRCA2_6
BRCA2_7
BRCA2_8

In [9]:
labels = []
for col in df_ml.index:
    if "Ctrl" in col:
        labels.append(0)
    elif "BRCA1" in col:
        labels.append(1)
    elif "BRCA2" in col:
        labels.append(2)

df_ml["target"] = labels

In [10]:
df_ml

ID_REF,1007_s_at,1053_at,117_at,121_at,1255_g_at,1294_at,1316_at,1320_at,1405_i_at,1431_at,...,AFFX-r2-Ec-bioD-5_at,AFFX-r2-P1-cre-3_at,AFFX-r2-P1-cre-5_at,AFFX-ThrX-3_at,AFFX-ThrX-5_at,AFFX-ThrX-M_at,AFFX-TrpnX-3_at,AFFX-TrpnX-5_at,AFFX-TrpnX-M_at,target
Ctrl_1,5.435103,7.733028,4.145030,6.072102,3.880355,8.244002,3.995260,3.894231,10.119957,3.601694,...,12.048695,13.735933,12.943992,3.882484,3.687871,3.691945,3.597827,4.021169,3.863777,0
Ctrl_2,5.008329,7.777820,4.291544,6.128962,3.741581,7.863173,3.934177,4.029559,11.296112,3.667243,...,11.723586,13.578497,12.718998,4.068816,3.844632,3.960012,3.698280,3.904696,3.706466,0
Ctrl_3,5.231527,8.454897,4.379873,6.334051,3.671371,6.393570,4.026327,4.190585,8.828152,3.677338,...,11.231814,13.551922,12.607748,3.931702,3.886046,3.731470,3.542740,3.960613,3.667430,0
Ctrl_4,5.031998,8.019996,4.478607,5.892953,3.721694,7.702444,4.159512,3.866083,11.196986,3.741057,...,11.875629,13.650233,12.830786,4.012594,3.825091,3.820569,3.825216,3.916462,3.454849,0
Ctrl_5,4.985290,6.771159,4.529217,6.092043,3.561725,8.419192,4.085102,4.022460,12.239574,3.750783,...,12.192493,13.804774,13.117024,3.971345,3.755792,3.759238,3.674284,3.758008,3.743802,0
Ctrl_6,6.142334,6.955941,4.866893,6.625896,3.811393,8.918576,4.120550,3.759336,11.413107,3.881524,...,9.352556,12.653236,11.890298,4.083088,3.894394,3.830467,3.765297,3.859202,3.631228,0
Ctrl_7,5.004434,8.672567,4.274667,5.474148,3.765680,7.331135,3.961010,4.017860,9.783332,3.682349,...,11.683333,13.574553,12.720251,4.043005,3.866237,3.755747,3.608352,3.813247,3.638798,0
Ctrl_8,5.411374,5.346701,4.726105,6.113826,3.621480,9.121967,4.079779,3.982694,10.602650,3.601726,...,12.087999,13.610194,12.912414,4.042596,3.714798,3.675765,3.782761,3.887486,3.655408,0
Ctrl_9,5.116332,7.446739,4.533870,6.053390,3.631466,8.420907,3.949763,3.994140,10.701429,3.648642,...,11.716284,13.528714,12.794530,3.944137,3.759497,3.803606,3.704745,3.869344,3.673831,0
BRCA1_1,5.284818,6.360131,10.066502,6.294137,3.681249,8.145534,4.228227,4.046465,11.819785,3.725276,...,12.062512,13.832867,13.224076,3.868354,3.711933,3.667778,3.585338,3.806914,3.579744,1
BRCA1_2,5.182803,7.902398,4.474714,6.042888,3.685221,7.580642,3.993735,4.147528,11.884071,3.679578,...,10.727166,12.965246,11.967667,4.007888,3.807003,3.942536,3.758908,3.727186,3.666670,1
BRCA1_3,5.456290,7.961362,4.330880,5.740115,3.596858,7.923142,3.977801,3.738986,11.806669,3.678737,...,11.834278,13.773880,12.981848,3.923956,3.698615,3.683854,3.669560,3.920549,3.654250,1
BRCA1_4,5.048849,8.229409,4.344952,5.674960,3.625883,7.775083,3.889287,3.924827,9.783927,3.570605,...,11.834547,13.512184,12.792800,3.734998,3.614176,3.724816,3.748796,3.970004,3.720680,1
BRCA1_5,5.087956,8.121414,4.355170,5.823128,3.564516,7.826739,4.154478,3.979360,8.688305,3.681539,...,12.016573,13.725189,12.963478,4.066847,3.900176,3.887271,3.635982,3.698335,3.719636,1
BRCA1_6,4.848453,7.958433,4.535119,6.300954,3.585755,8.275643,4.054460,4.137502,9.797972,3.672554,...,11.713628,13.610190,12.736113,4.041965,3.793307,3.824060,3.719136,3.734669,3.666160,1
BRCA1_7,5.340628,6.686733,11.946442,6.160760,3.676803,8.471139,3.948406,3.858988,11.154461,3.686303,...,11.956013,13.649715,12.945990,3.823251,3.859160,3.718513,3.692245,3.959998,3.662488,1
BRCA1_8,5.054647,7.167523,5.174017,6.312075,3.873683,8.621004,4.138326,3.889807,9.228351,3.694851,...,12.013282,13.609799,12.786031,4.056088,3.879627,3.805192,3.839517,3.843121,3.541297,1
BRCA1_9,5.436515,7.124138,5.487212,5.850466,3.666752,8.199452,3.975198,3.892871,11.128237,3.705859,...,11.879274,13.638843,12.831620,3.846474,3.719482,3.582174,3.576707,3.795824,3.606803,1
BRCA2_1,5.344158,6.593446,4.193879,6.021123,3.682486,8.079504,3.911734,4.109134,11.706726,3.852377,...,11.491159,13.474309,12.771478,3.815209,3.694363,3.575282,3.646838,3.579390,3.655582,2
BRCA2_2,5.535932,6.704074,4.597297,5.957165,3.604368,8.674645,4.084331,3.927564,11.781463,3.760567,...,11.656128,13.637365,12.850998,3.901003,3.878833,3.718253,3.620707,3.728518,3.590841,2
BRCA2_3,5.540570,7.557785,4.634234,6.439730,3.706883,8.158692,4.178522,3.977503,9.537391,3.770318,...,11.372583,13.395606,12.647765,3.846352,3.786138,3.722546,3.742525,3.906150,3.544716,2
BRCA2_4,5.351259,7.502817,4.518198,5.790195,3.693750,7.248585,3.944306,4.050683,10.537709,3.644094,...,11.750792,13.640210,12.943757,4.151427,3.789401,3.823395,3.732035,3.801924,3.665411,2
BRCA2_5,5.646676,7.518530,5.785436,6.411545,3.822298,7.991346,4.175725,3.951112,9.951454,3.708952,...,11.689889,13.666230,12.898545,3.766982,3.823888,3.806543,3.603609,3.810379,3.571417,2
BRCA2_6,5.459020,7.804092,4.183698,6.368793,3.863786,8.281895,3.848689,3.879350,11.249952,3.803046,...,11.299600,13.363030,12.446828,3.936198,3.941091,3.804492,3.616117,3.771551,3.634231,2
BRCA2_7,5.289579,7.434408,4.249086,6.064548,3.619982,8.035926,4.005591,3.974861,11.442377,3.847964,...,11.530820,13.712898,12.955113,4.080084,3.704182,3.821633,3.546395,3.665810,3.602096,2
BRCA2_8,5.471318,6.742815,4.489095,5.786747,3.692030,8.610116,4.191129,3.988412,11.768811,3.857082,...,11.633021,13.586853,12.883775,3.830499,3.788163,3.675097,3.562896,3.751692,3.570864,2

In [18]:
df_ml.shape

(26, 22278)

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

X = df_ml.drop("target", axis=1)
y = df_ml["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [12]:
model = RandomForestClassifier(n_estimators=200)
model.fit(X_train, y_train)

pred = model.predict(X_test)
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.50      0.33      0.40         3
           2       0.50      1.00      0.67         1

    accuracy                           0.50         6
   macro avg       0.50      0.61      0.52         6
weighted avg       0.50      0.50      0.48         6

In [13]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Calculate metrics
accuracy = accuracy_score(y_test, pred)
precision = precision_score(y_test, pred, average='weighted')
recall = recall_score(y_test, pred, average='weighted')
f1 = f1_score(y_test, pred, average='weighted')

# Print results
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1 Score:  {f1:.4f}")

Accuracy:  0.5000
Precision: 0.5000
Recall:    0.5000
F1 Score:  0.4778

In [14]:
from sklearn.feature_selection import VarianceThreshold

var_sel = VarianceThreshold(threshold=0.0)
X_train_v = var_sel.fit_transform(X_train)
X_test_v = var_sel.transform(X_test)


from sklearn.feature_selection import SelectKBest, mutual_info_classif

mi_sel = SelectKBest(score_func=mutual_info_classif, k=500)

X_train_mi = mi_sel.fit_transform(X_train_v, y_train)
X_test_mi = mi_sel.transform(X_test_v)


from sklearn.ensemble import RandomForestClassifier
import pandas as pd

rf = RandomForestClassifier(n_estimators=500, random_state=42)
rf.fit(X_train_mi, y_train)

importances = pd.Series(rf.feature_importances_)

top_idx = importances.sort_values(ascending=False).head(200).index

X_train_final = X_train_mi[:, top_idx]
X_test_final = X_test_mi[:, top_idx]

final_model = RandomForestClassifier(
    n_estimators=1000,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

final_model.fit(X_train_final, y_train)

pred = final_model.predict(X_test_final)

from sklearn.metrics import classification_report, accuracy_score

print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

Accuracy: 0.6666666666666666
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.33      0.50         3
           2       0.50      1.00      0.67         1

    accuracy                           0.67         6
   macro avg       0.72      0.78      0.66         6
weighted avg       0.81      0.67      0.63         6

In [15]:
# from sklearn.ensemble import RandomForestClassifier

# model = RandomForestClassifier(
#     n_estimators=500,
#     max_depth=None,
#     min_samples_split=2,
#     min_samples_leaf=1,
#     max_features="sqrt",
#     bootstrap=True,
#     class_weight="balanced",
#     random_state=42
# )

# model.fit(X_train_sel, y_train)

# pred = model.predict(X_test_sel)

NameError: name 'X_train_sel' is not defined

In [16]:
from sklearn.metrics import classification_report, accuracy_score

print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

Accuracy: 0.6666666666666666
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.33      0.50         3
           2       0.50      1.00      0.67         1

    accuracy                           0.67         6
   macro avg       0.72      0.78      0.66         6
weighted avg       0.81      0.67      0.63         6

In [17]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

# -----------------------------
# 1. Split features & target
# -----------------------------
X = df_ml.drop(columns=['target'])   # change 'target' if needed
y = df_ml['target']

# -----------------------------
# 2. Train-test split
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -----------------------------
# 3. Scaling (important for RFE with LR)
# -----------------------------
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# -----------------------------
# 4. Base model
# -----------------------------
model = LogisticRegression(max_iter=2000)

# -----------------------------
# 5. RFE setup
# -----------------------------
# change n_features_to_select as needed
rfe = RFE(estimator=model, n_features_to_select=50)

X_train_rfe = rfe.fit_transform(X_train_scaled, y_train)
X_test_rfe = rfe.transform(X_test_scaled)

# -----------------------------
# 6. Selected features
# -----------------------------
selected_features = X.columns[rfe.support_]

print("Selected Features:")
print(selected_features)

# -----------------------------
# 7. (Optional) train final model
# -----------------------------
model.fit(X_train_rfe, y_train)
print("Train accuracy:", model.score(X_train_rfe, y_train))
print("Test accuracy:", model.score(X_test_rfe, y_test))

KeyboardInterrupt:

# TWO STEP FEATURE SELECTION

In [19]:
pip install mrmr-selection

Collecting mrmr-selection
  Downloading mrmr_selection-0.2.8-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: category-encoders in /usr/local/lib/python3.12/dist-packages (from mrmr-selection) (2.9.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from mrmr-selection) (3.1.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from mrmr-selection) (4.67.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from mrmr-selection) (1.5.3)
Requirement already satisfied: pandas>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from mrmr-selection) (2.3.3)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.12/dist-packages (from mrmr-selection) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from mrmr-selection) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from mrmr-selection) (1.16.3)
Requirement already satisfied: polars>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from mrmr-selection) (1.35.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.3->mrmr-selection) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.3->mrmr-selection) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.3->mrmr-selection) (2025.3)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars>=0.12.5->mrmr-selection) (1.35.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category-encoders->mrmr-selection) (1.0.2)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category-encoders->mrmr-selection) (0.14.6)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->mrmr-selection) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->mrmr-selection) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.3->mrmr-selection) (1.17.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category-encoders->mrmr-selection) (26.0)
Downloading mrmr_selection-0.2.8-py3-none-any.whl (15 kB)
Installing collected packages: mrmr-selection
Successfully installed mrmr-selection-0.2.8
Note: you may need to restart the kernel to use updated packages.

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from mrmr import mrmr_classif

 

# -------------------------
# STEP 1: Fisher Score (ANOVA F-test)
# -------------------------
# reduce from 22278 → (e.g.) 2000 features
k_fisher = 2000

fisher_selector = SelectKBest(score_func=f_classif, k=k_fisher)

X_train_fisher = fisher_selector.fit_transform(X_train, y_train)
X_test_fisher = fisher_selector.transform(X_test)

selected_features_fisher = X_train.columns[fisher_selector.get_support()]
X_train_fisher = pd.DataFrame(X_train_fisher, columns=selected_features_fisher, index=X_train.index)
X_test_fisher = pd.DataFrame(X_test_fisher, columns=selected_features_fisher, index=X_test.index)

In [ ]:
X_train_mrmr = X_train_fisher[selected_features_mrmr]
X_test_mrmr = X_test_fisher[selected_features_mrmr]

In [22]:

# -------------------------
# STEP 2: mRMR Feature Selection
# -------------------------
# choose final features (important step)
k_mrmr = 1000

selected_features_mrmr = mrmr_classif(
    X=X_train_fisher,
    y=y_train,
    K=k_mrmr
)

X_train_mrmr = X_train_fisher[selected_features_mrmr]
X_test_mrmr = X_test_fisher[selected_features_mrmr]

# -------------------------
# Train Model (Random Forest)
# -------------------------
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

model.fit(X_train_mrmr, y_train)

pred = model.predict(X_test_mrmr)

print(classification_report(y_test, pred))

100%|██████████| 1000/1000 [03:11<00:00,  5.21it/s]

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.67      1.00      0.80         2
           2       1.00      1.00      1.00         2

    accuracy                           0.83         6
   macro avg       0.89      0.83      0.82         6
weighted avg       0.89      0.83      0.82         6

In [35]:
import torch
import torch.nn as nn
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
import numpy as np

# convert data
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)

# encode labels if needed
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)

y_train_tensor = torch.tensor(y_train_enc, dtype=torch.long)
y_test_tensor = torch.tensor(y_test_enc, dtype=torch.long)

In [36]:
class MLP(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(MLP, self).__init__()
        
        self.net = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.5),

            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Dropout(0.5),

            nn.Linear(32, num_classes)
        )

    def forward(self, x):
        return self.net(x)

In [37]:
input_dim = X_train_tensor.shape[1]
num_classes = len(np.unique(y_train_enc))

model = MLP(input_dim, num_classes)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

epochs = 300

for epoch in range(epochs):
    model.train()
    
    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 50 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")


# before scaling
        
# Epoch 50, Loss: 1.1045
# Epoch 100, Loss: 1.0983
# Epoch 150, Loss: 1.0968
# Epoch 200, Loss: 1.0978
# Epoch 250, Loss: 1.0980
# Epoch 300, Loss: 1.1004

# After scaling

# Epoch 50, Loss: 0.0091
# Epoch 100, Loss: 0.0093
# Epoch 150, Loss: 0.0030
# Epoch 200, Loss: 0.0001
# Epoch 250, Loss: 0.0018
# Epoch 300, Loss: 0.0035

Epoch 50, Loss: 0.0091
Epoch 100, Loss: 0.0093
Epoch 150, Loss: 0.0030
Epoch 200, Loss: 0.0001
Epoch 250, Loss: 0.0018
Epoch 300, Loss: 0.0035

In [38]:
model.eval()
with torch.no_grad():
    preds = model(X_test_tensor)
    predicted_classes = torch.argmax(preds, dim=1).numpy()

print(classification_report(y_test_enc, predicted_classes))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.50      0.50      0.50         2
           2       1.00      1.00      1.00         2

    accuracy                           0.67         6
   macro avg       0.67      0.67      0.67         6
weighted avg       0.67      0.67      0.67         6

In [27]:
X_train_mrmr.head()

ID_REF,202653_s_at,216150_at,208859_s_at,205702_at,218668_s_at,217982_s_at,220387_s_at,215639_at,212476_at,203425_s_at,...,213650_at,206454_s_at,208238_x_at,219750_at,204312_x_at,217649_at,202788_at,208175_s_at,206992_s_at,218273_s_at
BRCA2_6,8.702440,4.051646,7.219378,4.588540,9.656269,11.549638,5.194255,4.245383,7.499246,4.160274,...,6.591704,4.009873,6.308110,3.456673,7.932327,4.233775,8.875352,3.424777,6.539763,6.703262
Ctrl_2,7.901688,4.240816,5.441903,4.838593,7.936212,11.210559,4.936877,4.055565,6.524386,4.374027,...,5.024861,4.126943,5.508501,3.512423,8.443288,3.743171,9.480401,3.611295,7.265852,6.493302
Ctrl_3,7.979919,4.182075,5.875870,4.767198,8.391518,11.162336,3.924286,3.866115,6.878005,4.495007,...,4.956350,4.163025,5.987162,3.713398,8.261477,3.771279,9.682530,3.671143,7.017366,6.293879
Ctrl_9,8.135665,4.237286,5.477795,4.742217,7.667205,11.291894,5.080845,3.904688,6.587646,4.318803,...,5.888964,4.080319,6.164936,3.587146,8.503997,3.759305,9.156740,3.710591,7.037848,6.087747
BRCA1_4,7.791013,4.006753,5.591460,4.980667,7.886616,10.944910,6.041785,3.927643,6.654201,4.193689,...,5.304039,4.183670,5.728973,3.668398,8.528192,3.704380,10.186724,3.599712,6.640494,5.810732

In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_mrmr)
X_test_scaled = scaler.transform(X_test_mrmr)

In [31]:
X_test_scaled[0]

array([ 1.91635722e+00, -5.28510144e-01,  8.84020114e-01, -5.50004075e-01,
        1.17601463e+00,  1.88417416e+00,  1.08431997e+00, -3.53364712e-01,
        1.73457870e+00, -1.23312230e+00, -9.48205999e-01, -1.18019903e+00,
        1.10760505e+00, -2.18752365e+00,  3.46232872e-01, -1.12716045e+00,
        2.15992452e-01, -9.56676579e-01, -4.73317431e-01,  1.83737196e+00,
       -9.02660646e-01,  9.81103312e-01, -2.05403361e+00,  1.76219743e+00,
       -4.22054187e-01,  1.25930991e+00,  1.22923336e+00, -1.84355056e-01,
        1.78868061e+00, -3.78836407e-01, -8.40540384e-01,  1.08074293e+00,
       -1.52353194e+00,  2.03810171e+00,  4.93987179e-01,  1.09730857e+00,
        5.69205219e-01, -1.41056640e+00, -3.94937911e-01,  1.40891939e+00,
        1.12571197e+00,  2.80890802e-01, -1.99318022e+00, -3.06178228e-01,
        6.92620874e-01,  1.04577911e-01, -5.70534246e-01,  5.67748527e-01,
       -1.68762769e-01,  1.55624519e+00, -1.00610076e+00,  1.55628388e+00,
       -8.84143532e-01,  1.09518849e+00, -1.23396274e+00, -9.10965459e-02,
        1.30226687e+00, -7.00958166e-01, -1.34258644e-02,  1.21595209e+00,
        1.02320911e+00,  1.20599090e+00,  1.74899921e+00, -1.06373926e+00,
        1.65871792e-01, -1.56075318e+00, -1.73548092e+00, -1.35949313e+00,
        1.81151468e+00, -3.33547718e-01, -8.22030705e-01,  6.83818842e-02,
       -1.19069202e+00,  1.43460367e+00, -2.08148705e+00, -6.70075711e-01,
        6.15481507e-01,  1.47757889e+00, -1.96727302e+00,  7.18302506e-01,
        1.80819588e+00, -1.77017983e+00, -4.10688170e-01, -4.28592645e-03,
       -1.44375265e+00, -3.19760350e-01,  1.51586476e+00,  1.73613253e-01,
        3.38780647e-01, -4.80001748e-01,  1.46857861e+00, -1.54843979e+00,
       -9.24266126e-01, -1.48223076e+00,  7.93337067e-01,  1.67027142e+00,
       -6.41409408e-01, -8.89764740e-01, -4.45556987e-01,  1.27050694e+00,
       -5.04532545e-01, -8.12592953e-01, -6.55753795e-01, -7.29814442e-01,
       -8.25440134e-01,  1.33651233e+00, -1.75558644e+00,  9.05368268e-01,
       -6.61073651e-01, -2.48849558e+00,  1.16287318e+00, -1.44306305e+00,
       -1.84585670e+00,  1.05982237e+00, -1.24708107e+00,  1.83348903e+00,
       -1.91690057e+00,  1.57583091e+00, -1.35106466e+00,  7.20319084e-01,
        3.32318606e-01,  1.16110444e-01,  1.32251553e+00, -8.08798388e-01,
        1.72624066e+00, -6.10584413e-01,  5.29837913e-02,  1.14731642e+00,
        5.34663273e-01, -1.21100827e+00, -2.22248590e+00,  1.03408476e-01,
        5.64808247e-02,  1.11408677e+00,  1.56407480e+00, -2.33132502e+00,
       -1.38712317e-01,  6.57624791e-01, -3.79174275e-01, -1.91738347e+00,
        1.41019945e+00,  1.08863663e+00, -1.45151965e+00, -2.47772828e-01,
       -1.29411716e+00, -1.99963119e+00, -1.67841165e+00,  1.32702145e+00,
       -6.88787606e-01,  1.44440243e+00,  1.11135616e+00, -1.88625583e+00,
       -5.11056716e-01, -1.26575431e+00, -1.19486732e+00,  1.51975219e+00,
        2.02083647e-01,  1.59836038e-01, -4.78252139e-01,  4.24531651e-01,
       -1.19016527e+00, -8.64208558e-01, -9.45579339e-01, -9.55123387e-01,
       -8.42909494e-01,  1.33149164e+00, -1.14100282e+00, -1.25645699e+00,
       -1.44529198e+00, -3.04152438e-01,  1.36017384e+00, -8.35714459e-01,
       -6.83921106e-01,  1.83365585e-01, -1.71232166e+00, -1.13421450e+00,
       -5.13914258e-01,  7.54922728e-01,  1.47559814e+00, -7.20895099e-01,
        2.15319784e-01, -4.41004599e-01, -1.45709241e+00,  2.41136808e+00,
       -1.68508069e+00, -2.30440669e+00, -1.53446103e+00, -1.11202354e+00,
        2.58103281e+00,  8.31025473e-01,  7.11816736e-01, -4.12303502e-01,
        1.16570170e+00,  5.78904868e-01, -4.31570590e-01,  6.13495778e-01,
       -8.84419817e-01,  9.53602424e-02, -7.82872227e-01, -1.34390820e+00,
       -8.09287238e-01,  1.31727440e+00, -1.42281869e+00, -9.03543747e-01,
        8.13687725e-03,  1.17178292e+00, -1.13195829e+00, -2.58338695e+00,
       -1.45367767e-01, -6.10065611e-01, -1.51414108e+00,  6.71647987e-01,
       -5.91139357e-01, -8.69636888e-01,  1.10726652e+00, -2.16686835e-01,
       -4.76178891e-01,  1.51487864e+00,  9.03378244e-04,  1.64639993e+00,
       -1.80836224e+00, -3.82954681e-01, -1.03689366e+00, -6.23762723e-02,
        1.46185337e+00,  1.57653034e+00,  7.61610779e-03, -1.02588812e+00,
        2.09463986e-01, -2.77649896e+00,  1.57233648e+00,  4.35035570e-01,
       -2.09013471e+00,  8.68559774e-01,  4.88333811e-01, -3.18512853e-01,
       -1.39444627e+00,  1.19006443e+00, -1.48410351e+00,  1.47553864e+00,
       -2.00596344e+00, -8.31162544e-01, -1.26172373e+00,  2.61538992e-01,
       -6.61676977e-02, -6.38314650e-01, -7.30712582e-01, -9.37157821e-01,
        6.09685260e-02, -1.30797071e+00, -6.54395561e-01,  8.25122235e-01,
       -1.14713088e+00, -5.04667199e-01, -1.07850114e+00,  1.52766875e+00,
        2.40499635e-01, -3.86541792e-01,  2.82860982e-01, -7.25699584e-01,
        1.93681754e+00,  5.23375385e-01,  2.26581905e-01,  5.36752163e-01,
        5.65450894e-01, -1.92110933e+00,  1.54074119e+00, -6.12306257e-01,
       -1.16220860e+00, -1.18160055e+00,  1.39524301e-02, -7.10008930e-01,
        7.07872270e-01,  1.43434645e+00, -1.69204453e+00, -6.42448207e-01,
       -9.13980896e-01, -8.82612576e-01, -1.06698635e+00, -1.27890080e+00,
        8.54482564e-01, -2.23800196e-01,  2.56918602e+00,  1.27030921e+00,
       -5.12873409e-01,  1.86873963e+00, -5.43241446e-01, -1.98247606e+00,
        1.67549493e+00, -9.83189040e-01, -9.82829784e-01,  2.95742548e+00,
        7.72308674e-01,  7.16400999e-01,  1.41222258e+00, -1.00076212e-01,
        3.16087982e-01, -4.07295474e-01,  1.24345028e+00, -3.59638358e-01,
       -6.90455676e-01,  1.06541360e+00, -1.20686013e-01, -1.58152155e+00,
        1.13120309e+00, -1.05593811e+00,  1.52092746e+00,  6.51990797e-01,
        1.30020251e+00, -2.73877779e-01,  3.19536331e-01, -1.21088872e-01,
        1.21019412e-01, -1.57924063e-01, -1.04879702e+00, -5.12489099e-01,
       -8.96872708e-01, -4.04183073e-01, -4.32476569e-01, -4.68112204e-01,
       -5.70884838e-01,  6.35600375e-01, -2.04436697e-01, -1.42863879e+00,
       -1.39923966e+00, -2.18187794e+00, -2.86244756e+00, -7.62185879e-01,
        1.62232359e-01, -1.97556129e+00, -3.59836353e-01, -1.61994228e+00,
        1.76365331e+00,  1.10309208e+00, -2.33268676e-01, -6.71914417e-01,
       -7.91546912e-01,  1.03594783e-01, -4.98181908e-01, -9.85194570e-01,
       -2.02860574e+00,  3.72508667e-01, -1.23983970e-01, -8.00468995e-01,
       -1.26384011e+00, -2.62559398e-01, -2.14551712e+00,  2.74130767e+00,
        5.68524106e-01, -7.51890347e-01,  3.37150324e-01,  6.71992970e-01,
       -4.87553033e-01, -9.35466274e-01, -8.77156730e-01, -1.41871290e+00,
       -4.25614119e-02,  3.68165270e-01,  1.14012607e+00, -1.11136130e+00,
        3.91508486e-01, -9.92212559e-01,  8.06084321e-01, -1.07699412e+00,
        1.97734570e+00, -3.85047085e-01, -1.05254546e+00, -8.83830352e-01,
       -1.80445155e+00,  1.38795336e+00, -3.84927719e-01, -2.94353434e-02,
        4.08344243e-01,  9.15626723e-01, -3.11784012e-01,  1.25970166e+00,
       -1.21415860e+00, -3.14263657e+00, -2.37699595e+00, -1.40805996e+00,
        1.62814670e+00,  8.94782125e-01, -3.23203689e+00, -1.32530626e+00,
        1.47984212e+00, -1.05648960e+00,  1.58025425e+00,  7.48368336e-01,
       -1.13064357e+00, -1.88834447e+00, -7.60205258e-01,  2.22688291e-01,
       -2.87061091e-02, -6.15127840e-01, -6.23943266e-01,  4.12389617e-01,
        4.90924105e-01, -6.33075491e-01, -3.84611926e-01, -8.20942036e-01,
       -7.80543323e-01,  1.55364473e+00,  1.34439121e+00, -1.10743841e+00,
       -8.52134798e-02,  1.75405363e-01, -9.11659313e-01, -9.89962974e-01,
       -6.79989438e-01,  9.71851440e-01,  9.56461988e-01,  1.38034008e+00,
       -1.84976628e+00, -3.56558686e-01,  1.54165334e+00,  8.42901620e-01,
        8.28016464e-02,  1.59247434e-01, -8.12206704e-01, -1.68802674e-01,
        1.98872443e+00,  2.65028132e-01, -1.35533122e+00,  7.29230100e-01,
       -7.00850283e-01,  2.03963289e+00, -9.23612891e-01,  1.08691544e+00,
        1.09968768e+00,  3.24602657e-01,  1.59786267e+00, -1.74869056e+00,
       -6.89933421e-01, -3.25350877e-01, -1.23910990e+00, -9.70073247e-01,
       -1.89042996e-01, -3.63418992e-01,  5.42383276e-01,  1.30712327e-01,
        9.19426666e-01,  1.45090985e+00,  4.34425482e-01, -4.35184840e-03,
        1.16141894e+00, -7.77805415e-01, -1.05639288e+00,  1.89840854e+00,
        1.04409644e+00,  1.06580760e+00, -5.11023064e-01, -1.05957850e+00,
        4.99290484e-01,  5.83190288e-01, -5.98859245e-01,  1.42495411e-02,
        9.19643966e-01, -2.16136636e+00, -1.37398068e-01, -5.56313952e-01,
       -1.65133381e+00,  1.22908810e+00, -1.92626941e+00, -8.64683287e-01,
        1.71941821e+00,  1.11192680e+00, -2.64191331e+00, -1.34544018e+00,
       -1.41393933e+00, -1.64083179e+00, -2.12559456e-01,  1.84233206e-01,
       -1.56134097e+00, -1.26397014e+00, -1.54897760e+00, -1.41284946e+00,
       -8.08590396e-01,  8.55724975e-01, -5.37743122e-01, -6.95955796e-01,
        1.69707840e+00, -3.74540344e-01, -1.05278062e+00, -4.00781766e-01,
       -1.49165577e-01,  3.00605923e-01, -1.40520483e+00,  1.94052082e+00,
        2.90694104e-01,  1.49319259e+00, -1.27698675e+00, -7.26641088e-01,
       -3.76170712e-01, -5.24415880e-01,  5.26098414e-01, -1.42770698e+00,
       -4.36910860e-01, -1.27023103e+00,  2.88188800e-01, -1.23078133e+00,
       -5.70962178e-02,  1.41517891e+00,  2.80610996e-01, -5.74689381e-01,
        3.57478449e-01,  1.47089959e+00,  7.41168684e-02, -1.63844313e+00,
       -1.97752522e+00,  7.25630956e-01, -6.13421910e-01, -1.10009473e+00,
       -1.15547433e+00, -3.23837882e+00, -1.10435238e-01, -7.28429907e-01,
       -5.65102525e-01, -7.00066462e-02, -1.17970012e+00,  6.82232311e-01,
       -2.36426140e+00,  8.27130749e-01, -1.94881748e+00,  1.53440974e+00,
       -6.09873990e-01, -3.27527531e+00,  6.02356346e-02, -1.66412239e+00,
        2.71260051e+00,  8.92926597e-01, -1.62817293e+00,  8.28836274e-01,
       -6.89698567e-01, -4.82717801e-01, -2.20618917e-01,  1.14725502e+00,
        1.83027081e-01, -8.68310439e-01, -2.30790923e+00, -2.08068777e-01,
       -1.00879945e+00,  8.38265630e-01,  9.04369067e-01, -1.45360659e+00,
        1.28468421e+00,  1.84168467e+00, -7.73493210e-01, -8.87061608e-01,
        7.42826221e-01, -1.29092935e+00, -1.03087384e+00, -3.77760678e-01,
        6.32878139e-01, -1.56351634e+00,  1.42982524e+00, -2.73276909e-01,
        2.38174953e+00, -1.66734853e-01, -2.08092652e-01,  3.78719267e-01,
        5.41165582e-02,  6.20391396e-01, -3.25378755e-01,  1.40008931e+00,
        8.18529200e-02, -1.18919235e+00, -1.35444208e+00,  7.41276827e-02,
        1.15412950e+00, -9.50486750e-01,  2.34339531e+00,  5.40013686e-01,
        1.92177350e-01,  1.70013231e+00, -1.82225339e-01,  1.58294501e+00,
        4.35352971e-01, -1.09713178e+00,  1.55480379e+00, -1.13729288e+00,
       -9.43627447e-01, -6.14471714e-01,  2.46346728e-01, -5.52201424e-01,
       -1.47560569e+00,  4.55867887e-01, -7.44811322e-01, -2.51535411e-01,
       -1.81057254e-01,  1.78230402e+00, -1.22438941e+00,  1.51784630e+00,
       -1.13858566e+00,  9.35158955e-01, -1.81354050e-02, -1.64895978e+00,
        4.59627154e-01,  1.51685290e+00,  5.07770177e-01,  1.59138735e+00,
        6.75799227e-01, -1.29374598e+00, -1.18348134e+00, -8.85093945e-01,
        1.16509617e+00, -8.45849057e-01, -2.95882021e-01, -1.49285450e+00,
       -5.86106398e-01, -2.85207199e-01,  1.52630383e+00, -1.49348674e+00,
       -1.01379426e+00,  1.10598950e-01, -1.72618122e+00, -1.35645214e+00,
       -2.15165867e+00, -5.73693981e-01, -1.69081040e-01,  3.10224393e-01,
        1.01596411e-01, -1.01362245e+00, -3.03528896e-01, -9.78611391e-01,
       -1.37934505e+00,  9.38229338e-01, -9.13125532e-01,  1.21810761e+00,
        9.54569521e-03, -1.02769141e+00,  2.19919699e+00, -2.03313475e+00,
       -1.51675621e+00, -1.58869606e+00,  6.20887971e-01, -4.11958312e-01,
       -1.08068507e+00, -8.81056285e-01, -1.61333539e+00, -1.87967437e-01,
        1.71530311e+00, -1.07683212e+00, -1.09972115e+00, -8.78440795e-01,
        2.27128610e+00, -4.47784300e-01, -9.47157424e-01, -1.12286060e+00,
       -4.61657739e-01, -8.37558023e-01, -1.40201200e+00,  1.81709077e+00,
       -2.53611391e+00, -2.12096800e+00, -6.93243982e-01, -8.50746716e-01,
        1.97401252e+00,  2.38593605e-01, -1.19163920e+00, -4.43215503e-01,
        8.63192770e-01, -1.70530302e-01,  1.82890428e+00, -6.16899543e-01,
       -1.37141266e+00,  2.00463576e+00,  6.08989391e-01, -1.42821156e+00,
       -8.73119132e-01, -2.08771775e+00, -1.03807183e+00,  1.64973468e-01,
       -1.27398378e+00,  1.36965394e+00,  1.51662098e+00,  4.01201365e-01,
       -1.85340565e-01, -6.76373628e-01, -7.00901889e-01, -8.76386427e-01,
        3.16330164e-01,  2.03624454e+00, -5.84847288e-01,  2.08893707e-01,
       -6.37042526e-04, -7.93967877e-01,  6.55263194e-01, -3.09911701e-01,
        2.13652468e-01, -1.04255675e+00, -2.34924764e-01, -1.57851805e+00,
       -6.91509917e-01, -3.35389521e-01, -3.52918801e+00,  2.72734018e-01,
       -1.02766173e+00, -6.46339250e-01,  2.57327566e-04, -1.26101651e+00,
       -1.18896560e+00, -2.17693235e+00,  1.45549541e-01, -1.65071815e+00,
       -2.77664990e-01,  2.82467024e-01,  9.87036914e-01, -4.96492900e-01,
        1.13552674e-01,  7.68050928e-01, -8.50621768e-01, -1.01220767e+00,
       -5.37345155e-01, -4.70834358e-01, -7.64619216e-01, -1.44277008e+00,
        1.24832331e+00,  8.43480954e-01, -4.25878354e-01, -1.76244378e-01,
       -7.83223676e-01,  1.69055824e+00, -7.62614674e-02, -9.75556760e-01,
       -5.33807033e-01, -6.54339159e-02, -1.42890706e+00, -9.48916755e-01,
       -1.46431966e+00,  1.37814799e+00,  1.97184887e-01, -1.35037607e+00,
       -1.02999776e+00, -8.32937190e-01, -1.13680035e+00, -2.06574933e+00,
       -1.11822626e+00,  1.20104673e+00, -2.21634031e-01, -1.50415748e-01,
        2.10454600e+00,  1.23839141e+00, -1.28933819e+00, -1.51914051e+00,
        1.72144184e+00,  2.07919562e-01, -7.69531489e-01, -1.58832996e+00,
       -1.86199783e+00, -7.96299140e-01, -3.60190871e-01, -1.51048219e+00,
        8.94113227e-01, -1.31871048e+00, -8.41507372e-01,  1.17839030e+00,
       -5.78804149e-01, -1.52642793e+00, -5.76573823e-01, -1.26160458e+00,
        2.76715137e-01, -2.67919667e+00, -1.01612705e+00,  2.88471589e+00,
       -1.77757858e+00,  5.12120687e-02, -6.80391039e-01, -1.43223604e+00,
        1.11859488e+00,  1.71279875e+00, -1.71922359e+00, -5.71149430e-01,
       -1.79104081e+00,  1.41161470e+00,  4.59508903e-01, -1.89470784e+00,
        1.94274542e-01,  6.26342932e-01,  1.04968271e+00, -1.45268523e+00,
        1.34726399e+00, -2.30251733e-01, -5.87151484e-02, -1.20685106e+00,
        1.56748915e+00,  3.26539620e-01, -2.07310338e+00,  1.20535527e+00,
       -8.44096980e-01, -4.94463797e-01,  2.22123345e+00,  1.93268400e+00,
       -7.74885172e-01,  1.19105382e+00,  5.01350258e-01, -7.57497208e-01,
       -3.70107254e-01, -3.02018969e-01, -6.48997887e-01, -1.35473140e+00,
       -1.25573895e+00, -4.07348314e-01,  1.70236197e+00,  7.23467274e-01,
       -9.46977968e-01, -2.33374537e+00, -7.18319450e-01, -6.55113482e-01,
        6.91967512e-01,  1.69945274e+00, -6.46058805e-02, -7.58683454e-01,
        4.57224967e-01,  5.69548040e-01,  2.64972220e-02, -1.29585002e+00,
       -2.22397837e+00,  1.22303403e+00,  4.08274315e-02, -9.46917893e-01,
       -1.33885128e+00, -3.12480818e-01, -1.28464116e-02,  1.59035907e-01,
       -1.24390120e+00, -1.35240879e+00, -3.90838673e-02, -3.70759425e-01,
        1.80439321e+00, -9.83024060e-02,  9.53103844e-01,  1.03176351e+00,
        2.20510303e-01, -1.42710104e+00, -9.87053272e-01,  1.87595220e+00,
       -1.38509199e+00, -1.65928357e-01,  1.17098529e+00, -9.05812059e-02,
        1.57304073e+00,  1.02589680e+00,  9.30899952e-01,  1.49167565e-01,
        4.25172261e-01, -1.60811625e+00,  1.20959558e+00,  5.06551538e-01,
       -3.12409019e-01, -2.19372169e-01,  8.38785464e-01, -1.07014817e+00,
       -3.00944387e-01,  3.33441172e-01,  4.07215060e-01,  1.97951735e-01,
       -1.08891825e+00, -1.81385018e+00,  2.41000946e+00, -7.16966174e-01,
       -1.64897070e+00,  1.85324609e-01, -1.32276276e-01,  7.36971267e-01,
        1.34300222e+00,  1.97498705e+00, -1.44745738e+00, -2.88511485e-01,
       -9.93927636e-01, -1.62885783e+00, -7.01272675e-01, -8.22975582e-01,
        1.70173173e+00,  1.00307444e+00, -7.38054215e-01, -1.69471880e+00,
       -2.03740092e+00,  5.76157934e-02, -4.96190767e-01, -6.70877741e-01,
       -2.86430426e-01, -1.10568300e+00,  6.95116899e-02, -5.74012108e-01,
        1.65590901e+00, -7.74390175e-01, -9.91540478e-01, -4.14689072e-01,
       -2.52295454e+00,  1.01780385e+00,  1.98982857e-01, -1.42502957e+00,
       -4.65747703e-01, -1.79378578e+00, -1.05438236e+00,  6.46103228e-01,
        1.12044265e+00,  8.96182619e-02,  4.25127625e-01,  2.43678664e-02,
       -1.73662862e+00,  1.03127883e+00,  8.98506833e-01, -1.64397389e+00,
       -8.88892759e-01,  1.95372338e+00,  2.94027248e+00, -2.36372981e-01,
       -4.20738214e-01, -2.90677251e-01,  2.34775557e+00,  1.45152089e+00,
        7.38741832e-01,  1.42409908e+00, -3.59450531e-02,  6.80071909e-01,
        1.64448365e+00, -8.44388089e-01, -1.16047151e+00, -1.48957437e-01,
        1.25720341e+00, -1.12417325e-01, -1.59340679e+00,  9.58239135e-01,
       -7.55690593e-01,  8.35889732e-02, -1.46857374e+00, -1.47628088e+00,
       -1.28437402e+00, -2.51196131e-01,  1.42776926e+00,  2.18185575e-01,
       -2.25030374e-01,  1.25906655e+00, -2.12645008e+00, -3.83982873e-01,
        1.17526520e+00,  6.03010262e-01, -7.71836495e-01, -4.85974906e-01,
        1.72304610e-01,  1.14506686e+00,  1.07051171e-01, -6.42237290e-01,
        1.07102700e-01, -1.31253245e-02, -1.88503465e+00, -1.50181874e+00,
       -1.78102826e-01, -1.61248373e+00, -1.29503044e+00, -6.65798249e-01,
       -1.65047300e-01, -3.71535902e-01, -1.45198035e+00, -2.03202668e+00,
       -6.60583075e-01, -1.16891778e+00,  7.58335085e-02,  1.66999869e+00,
       -4.11257745e-01, -5.42303905e-01, -1.07943868e+00, -7.42824187e-01,
       -1.18767155e+00,  1.86197912e-01, -1.51072436e+00, -3.01917106e-01,
       -2.30761108e-01,  7.05400461e-01,  4.38608311e-01, -4.98382894e-01,
        1.16213155e+00,  1.44767259e+00,  4.02192145e-01, -6.22861745e-01,
       -9.00328646e-01, -7.92444302e-01, -1.32188261e+00, -7.11715467e-01,
        8.30932704e-01,  9.27820437e-02,  3.12575283e-01, -4.15287711e-01,
       -6.57336792e-01,  1.56786104e+00, -4.21876044e-01, -1.48540024e+00,
        1.14622034e-01,  8.70935993e-01,  9.62581571e-01, -1.79030945e+00,
        1.95843920e+00, -1.06570576e+00, -2.86198916e+00,  1.90323659e-01,
       -9.76912378e-01, -6.91044990e-01, -1.53584397e-01,  1.72219619e-01])

In [39]:
import torch
import torch.nn as nn

class Autoencoder(nn.Module):
    def __init__(self, input_dim, latent_dim=16):
        super(Autoencoder, self).__init__()

        # Encoder
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 128),
            nn.ReLU(),
            nn.Linear(128, latent_dim)
        )

        # Decoder
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 128),
            nn.ReLU(),
            nn.Linear(128, input_dim)
        )

    def forward(self, x):
        z = self.encoder(x)
        out = self.decoder(z)
        return z, out

In [40]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)

ae = Autoencoder(input_dim=X_train_scaled.shape[1], latent_dim=16)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(ae.parameters(), lr=0.001)

for epoch in range(400):
    ae.train()

    z, recon = ae(X_train_tensor)
    loss = criterion(recon, X_train_tensor)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 50 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

Epoch: 0 Loss: 1.0087618827819824
Epoch: 50 Loss: 0.19962260127067566
Epoch: 100 Loss: 0.015343976207077503
Epoch: 150 Loss: 0.000244806898990646
Epoch: 200 Loss: 5.042943939770339e-06
Epoch: 250 Loss: 3.946700871892972e-06
Epoch: 300 Loss: 1.3645681974594481e-05
Epoch: 350 Loss: 1.5822941350052133e-05

In [41]:
ae.eval()
with torch.no_grad():
    X_train_latent = ae.encoder(torch.tensor(X_train_scaled, dtype=torch.float32)).numpy()
    X_test_latent = ae.encoder(torch.tensor(X_test_scaled, dtype=torch.float32)).numpy()

In [42]:
class Classifier(nn.Module):
    def __init__(self, input_dim, num_classes):
        super(Classifier, self).__init__()

        self.net = nn.Sequential(
            nn.Linear(input_dim, 32),
            nn.ReLU(),
            nn.Dropout(0.4),

            nn.Linear(32, 16),
            nn.ReLU(),

            nn.Linear(16, num_classes)
        )

    def forward(self, x):
        return self.net(x)

In [43]:
X_train_t = torch.tensor(X_train_latent, dtype=torch.float32)
X_test_t = torch.tensor(X_test_latent, dtype=torch.float32)

y_train_t = torch.tensor(y_train_enc, dtype=torch.long)

model = Classifier(input_dim=16, num_classes=len(set(y_train_enc)))

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epoch in range(300):
    model.train()

    out = model(X_train_t)
    loss = criterion(out, y_train_t)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 50 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

Epoch: 0 Loss: 1.1079367399215698
Epoch: 50 Loss: 0.5504888296127319
Epoch: 100 Loss: 0.1737828552722931
Epoch: 150 Loss: 0.03891025111079216
Epoch: 200 Loss: 0.052733004093170166
Epoch: 250 Loss: 0.009688802063465118

In [44]:
model.eval()
with torch.no_grad():
    preds = model(X_test_t)
    pred_labels = torch.argmax(preds, dim=1).numpy()

from sklearn.metrics import classification_report
print(classification_report(y_test_enc, pred_labels))

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.50      0.50      0.50         2
           2       1.00      1.00      1.00         2

    accuracy                           0.67         6
   macro avg       0.67      0.67      0.67         6
weighted avg       0.67      0.67      0.67         6

# TWO STEP FEATURE SELECITON

In [45]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from mrmr import mrmr_classif

# -------------------------
# Split data
# -------------------------
X = df_ml.drop("target", axis=1)
y = df_ml["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -------------------------
# STEP 1: Fisher Score (ANOVA F-test)
# -------------------------
# reduce from 22278 → (e.g.) 2000 features
k_fisher = 2000

fisher_selector = SelectKBest(score_func=f_classif, k=k_fisher)

X_train_fisher = fisher_selector.fit_transform(X_train, y_train)
X_test_fisher = fisher_selector.transform(X_test)

selected_features_fisher = X_train.columns[fisher_selector.get_support()]
X_train_fisher = pd.DataFrame(X_train_fisher, columns=selected_features_fisher, index=X_train.index)
X_test_fisher = pd.DataFrame(X_test_fisher, columns=selected_features_fisher, index=X_test.index)

# -------------------------
# STEP 2: mRMR Feature Selection
# -------------------------
# choose final features (important step)
k_mrmr = 100

selected_features_mrmr = mrmr_classif(
    X=X_train_fisher,
    y=y_train,
    K=k_mrmr
)

X_train_mrmr = X_train_fisher[selected_features_mrmr]
X_test_mrmr = X_test_fisher[selected_features_mrmr]

# -------------------------
# Train Model (Random Forest)
# -------------------------
# model = RandomForestClassifier(
#     n_estimators=200,
#     random_state=42,
#     class_weight="balanced"
# )

# model.fit(X_train_mrmr, y_train)

# pred = model.predict(X_test_mrmr)

# print(classification_report(y_test, pred))

#               precision    recall  f1-score   support

#            0       0.50      0.50      0.50         2
#            1       0.50      0.50      0.50         2
#            2       1.00      1.00      1.00         2

#     accuracy                           0.67         6
#    macro avg       0.67      0.67      0.67         6
# weighted avg       0.67      0.67      0.67         6

100%|██████████| 100/100 [00:21<00:00,  4.76it/s]

              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.50      0.50      0.50         2
           2       1.00      1.00      1.00         2

    accuracy                           0.67         6
   macro avg       0.67      0.67      0.67         6
weighted avg       0.67      0.67      0.67         6

In [46]:
import torch
import numpy as np

X_train = X_train_mrmr.values
X_test = X_test_mrmr.values

X_train_tensor = torch.tensor(X_train, dtype=torch.float32).unsqueeze(1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32).unsqueeze(1)

In [47]:
import torch.nn as nn
import torch.nn.functional as F

class AttCNN(nn.Module):
    def __init__(self, input_length, num_classes):
        super(AttCNN, self).__init__()

        # --------------------
        # 1D CNN block
        # --------------------
        self.conv1 = nn.Conv1d(1, 32, kernel_size=5, padding=2)
        self.conv2 = nn.Conv1d(32, 64, kernel_size=3, padding=1)

        # --------------------
        # Attention layer
        # --------------------
        self.attention = nn.Linear(64, 1)

        # --------------------
        # Fully connected
        # --------------------
        self.fc1 = nn.Linear(64, 32)
        self.fc2 = nn.Linear(32, num_classes)

        self.dropout = nn.Dropout(0.4)

    def forward(self, x):

        # CNN
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))   # (batch, channels, genes)

        # --------------------
        # Attention mechanism
        # --------------------
        x_perm = x.permute(0, 2, 1)  # (batch, genes, channels)

        attn_weights = torch.softmax(self.attention(x_perm), dim=1)

        x = torch.sum(x_perm * attn_weights, dim=1)  # context vector

        # --------------------
        # Dense layers
        # --------------------
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)

        return x

In [48]:
num_classes = len(np.unique(y_train))

model = AttCNN(
    input_length=X_train.shape[1],
    num_classes=num_classes
)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

y_train_tensor = torch.tensor(y_train_enc, dtype=torch.long)

epochs = 300

for epoch in range(epochs):
    model.train()

    outputs = model(X_train_tensor)
    loss = criterion(outputs, y_train_tensor)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 50 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 1.1364
Epoch 50, Loss: 1.0954
Epoch 100, Loss: 1.0834
Epoch 150, Loss: 1.0971
Epoch 200, Loss: 0.9780
Epoch 250, Loss: 0.7202

In [49]:
model.eval()

with torch.no_grad():
    preds = model(X_test_tensor)
    pred_labels = torch.argmax(preds, dim=1).numpy()

from sklearn.metrics import classification_report
print(classification_report(y_test_enc, pred_labels))

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         2
           1       0.00      0.00      0.00         2
           2       1.00      1.00      1.00         2

    accuracy                           0.67         6
   macro avg       0.50      0.67      0.56         6
weighted avg       0.50      0.67      0.56         6

In [50]:
import tensorflow as tf
from tensorflow.keras import layers, Model, regularizers

class AttentionLayer(layers.Layer):
    def __init__(self):
        super().__init__()

    def build(self, input_shape):
        self.uw = self.add_weight(
            shape=(input_shape[-1], 1),
            initializer="glorot_uniform",
            trainable=True
        )

    def call(self, inputs):
        # score: (batch, time, 1)
        score = tf.matmul(inputs, self.uw)

        # stable softmax (important fix)
        weights = tf.nn.softmax(tf.squeeze(score, axis=-1), axis=1)
        weights = tf.expand_dims(weights, axis=-1)

        # weighted sum
        context = inputs * weights
        return tf.reduce_sum(context, axis=1)

2026-05-03 07:18:38.494302: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777792718.682018      57 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777792718.736126      57 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1777792719.168808      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777792719.168836      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777792719.168839      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1777792719.168841      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

In [52]:
def build_att_cnn(input_shape, num_classes=3):

    inputs = layers.Input(shape=input_shape)

    # --------------------
    # CNN block
    # --------------------
    x = layers.Conv1D(
        64, 3, padding='same',
        activation='relu',
        kernel_regularizer=regularizers.l2(1e-4)
    )(inputs)

    x = layers.BatchNormalization()(x)

    x = layers.Conv1D(
        128, 3, padding='same',
        activation='relu',
        kernel_regularizer=regularizers.l2(1e-4)
    )(x)

    x = layers.Dropout(0.3)(x)

    # --------------------
    # Attention
    # --------------------
    x = AttentionLayer()(x)

    # --------------------
    # Fully connected
    # --------------------
    x = layers.Dense(
        64, activation='relu',
        kernel_regularizer=regularizers.l2(1e-4)
    )(x)

    x = layers.Dropout(0.4)(x)

    x = layers.Dense(32, activation='relu')(x)

    # --------------------
    # Output
    # --------------------
    if num_classes == 2:
        outputs = layers.Dense(1, activation='sigmoid')(x)
    else:
        outputs = layers.Dense(num_classes, activation='softmax')(x)

    return Model(inputs, outputs, name="Improved_AttCNN")

In [53]:
model = build_att_cnn(input_shape=(X_train.shape[1], 1), num_classes=3)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=30,
    restore_best_weights=True
)

history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=300,
    batch_size=4,
    callbacks=[early_stop],
    verbose=1
)

I0000 00:00:1777792756.788512      57 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15511 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0

Epoch 1/300

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1777792760.053689     408 service.cc:152] XLA service 0x7f4e58010460 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1777792760.053720     408 service.cc:160]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
I0000 00:00:1777792760.520739     408 cuda_dnn.cc:529] Loaded cuDNN version 91002

1/4 ━━━━━━━━━━━━━━━━━━━━ 16s 6s/step - accuracy: 0.2500 - loss: 1.1400

I0000 00:00:1777792763.652987     408 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

4/4 ━━━━━━━━━━━━━━━━━━━━ 6s 263ms/step - accuracy: 0.4667 - loss: 1.0962 - val_accuracy: 0.5000 - val_loss: 1.0109
Epoch 2/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.2000 - loss: 1.1430 - val_accuracy: 0.5000 - val_loss: 1.0073
Epoch 3/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.3833 - loss: 1.1315 - val_accuracy: 0.5000 - val_loss: 1.0052
Epoch 4/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.2333 - loss: 1.1211 - val_accuracy: 0.5000 - val_loss: 1.0039
Epoch 5/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.2750 - loss: 1.1374 - val_accuracy: 0.5000 - val_loss: 1.0007
Epoch 6/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4167 - loss: 1.1114 - val_accuracy: 0.5000 - val_loss: 1.0029
Epoch 7/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4583 - loss: 1.0874 - val_accuracy: 0.5000 - val_loss: 1.0030
Epoch 8/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5917 - loss: 1.0407 - val_accuracy: 0.5000 - val_loss: 1.0056
Epoch 9/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.2417 - loss: 1.1078 - val_accuracy: 0.5000 - val_loss: 1.0062
Epoch 10/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4500 - loss: 1.0511 - val_accuracy: 0.5000 - val_loss: 1.0073
Epoch 11/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3167 - loss: 1.1801 - val_accuracy: 0.5000 - val_loss: 1.0071
Epoch 12/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.2750 - loss: 1.1797 - val_accuracy: 0.5000 - val_loss: 1.0066
Epoch 13/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4417 - loss: 1.0929 - val_accuracy: 0.5000 - val_loss: 1.0073
Epoch 14/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.2833 - loss: 1.2098 - val_accuracy: 0.5000 - val_loss: 1.0115
Epoch 15/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5750 - loss: 1.0033 - val_accuracy: 0.5000 - val_loss: 1.0136
Epoch 16/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4333 - loss: 1.0637 - val_accuracy: 0.5000 - val_loss: 1.0121
Epoch 17/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.3583 - loss: 1.0971 - val_accuracy: 0.5000 - val_loss: 1.0112
Epoch 18/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.3000 - loss: 1.1245 - val_accuracy: 0.5000 - val_loss: 1.0108
Epoch 19/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5250 - loss: 1.0401 - val_accuracy: 0.5000 - val_loss: 1.0120
Epoch 20/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3583 - loss: 1.1558 - val_accuracy: 0.5000 - val_loss: 1.0124
Epoch 21/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.2750 - loss: 1.1013 - val_accuracy: 0.5000 - val_loss: 1.0132
Epoch 22/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.3500 - loss: 1.0152 - val_accuracy: 0.5000 - val_loss: 1.0153
Epoch 23/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3250 - loss: 1.0671 - val_accuracy: 0.5000 - val_loss: 1.0171
Epoch 24/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3583 - loss: 1.1597 - val_accuracy: 0.5000 - val_loss: 1.0190
Epoch 25/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 1.0407 - val_accuracy: 0.7500 - val_loss: 1.0221
Epoch 26/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3583 - loss: 1.1164 - val_accuracy: 0.5000 - val_loss: 1.0246
Epoch 27/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3917 - loss: 1.1303 - val_accuracy: 0.5000 - val_loss: 1.0258
Epoch 28/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3917 - loss: 1.1300 - val_accuracy: 0.5000 - val_loss: 1.0270
Epoch 29/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4667 - loss: 1.0775 - val_accuracy: 0.5000 - val_loss: 1.0281
Epoch 30/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3333 - loss: 1.1123 - val_accuracy: 0.5000 - val_loss: 1.0292
Epoch 31/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5083 - loss: 1.0644 - val_accuracy: 0.5000 - val_loss: 1.0306
Epoch 32/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3667 - loss: 1.2210 - val_accuracy: 0.5000 - val_loss: 1.0324
Epoch 33/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.3250 - loss: 1.1073 - val_accuracy: 0.5000 - val_loss: 1.0347
Epoch 34/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.3167 - loss: 1.0873 - val_accuracy: 0.5000 - val_loss: 1.0370
Epoch 35/300
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4083 - loss: 1.0901 - val_accuracy: 0.5000 - val_loss: 1.0390

In [54]:
pred = model.predict(X_test)
pred_labels = tf.argmax(pred, axis=1).numpy()

from sklearn.metrics import classification_report
print(classification_report(y_test, pred_labels))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 509ms/step
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.33      1.00      0.50         2
           2       0.00      0.00      0.00         2

    accuracy                           0.33         6
   macro avg       0.11      0.33      0.17         6
weighted avg       0.11      0.33      0.17         6

In [56]:
# print(X_train.shape)
# print(X_test.shape)

(20, 100)
(6, 100)